# These are supported funding model platforms

github: [MDAMINULSARDAR]   # তোমার GitHub ইউজারনেম
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
lfx_crowdfunding: 
custom: [
  "https://facebook.com/100071880593545",
  "https://t.me/aminulsordar",
  "mailto:aminulsordar04@gmail.com"
]
