name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prevent overlap
        run: |
          echo "Checking for running workflows..."
          RUNNING=$(gh run list --workflow="Run.yml" --status=in_progress --limit 1 --json databaseId | jq '.[0]')
          if [ "$RUNNING" != "null" ]; then
            echo "Another run is already in progress. Exiting."
            exit 0
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Start bot
        run: npm start

      - name: Wait before restart
        run: sleep 10

      - name: Self-dispatch to restart
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow: "Run.yml"
          ref: ${{ github.ref }}
