name: Node.js CI

on:
  schedule:
    - cron: "59 */6 * * *" # Every 6 hours at minute 59 (~5h59m apart)
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prevent overlap
        run: |
          RUNNING=$(gh run list --workflow="Run.yml" --status=in_progress --limit 1 --json databaseId | jq '.[0]')
          if [ "$RUNNING" != "null" ]; then
            echo "Another run is in progress. Exiting."
            exit 0
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm install
      - run: npm start
